#!/bin/bash

echo "1" > /sys/module/processor/parameters/ignore_ppc

echo "2400000" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
echo "2400000" > /sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq
echo "2400000" > /sys/devices/system/cpu/cpu2/cpufreq/scaling_max_freq
echo "2400000" > /sys/devices/system/cpu/cpu3/cpufreq/scaling_max_freq

cpufreq-set -g performance -c 0
cpufreq-set -g performance -c 1
cpufreq-set -g performance -c 2
cpufreq-set -g performance -c 3

cpufreq-set -f 2.40GHz -c 0
cpufreq-set -f 2.40GHz -c 1
cpufreq-set -f 2.40GHz -c 2
cpufreq-set -f 2.40GHz -c 3

